name: inkflow-ai

services:
  # 后端API服务
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inkflow-backend
    env_file:
      - .env
    environment:
      - DEBUG=false
    ports:
      - "20001:20001"

    networks:
      - inkflow-network
      - database-network
    volumes:
      - .:/app

networks:
  inkflow-network:
    driver: bridge
  database-network:
    external: true
    name: database-network